"""
Calibration analysis script to compute robot base frame from circle fitting results.

This script processes the data generated by 0_circle_fitting.py to:
1. Fit lines to circle centers for j0 and j1 joints
2. Visualize data quality
3. Compute the robot base frame transformation matrix
"""

import json
import os
import numpy as np
import xml.etree.ElementTree as ET
from skspatial.objects import Line, Point, Vector, Plane
from skspatial.plotting import plot_3d
import matplotlib.pyplot as plt
import pybullet_planning as pp

from config_loader import load_config, get_robot_urdf, get_shoulder_pan_joint_name, HERE
from logging_utils import setup_logger

# Load configuration
config = load_config()
date_folder = config['date_folder']
robot_name = config['robot_name']
arm = config['arm']

URDF_FILE = get_robot_urdf(robot_name)
SHOULDER_PAN_JOINT_NAME = get_shoulder_pan_joint_name(robot_name, arm)

# Configure logging with colored output
log_file = os.path.join(HERE, date_folder, 'calibration_analysis_log.txt')
logger = setup_logger(log_file=log_file)

# File paths
j0_data_file_path = os.path.join(HERE, date_folder, 'j0', 'j0_analysis.json')
j1_data_file_path = os.path.join(HERE, date_folder, 'j1', 'j1_analysis.json')
output_dir = os.path.join(HERE, date_folder)


def load_analysis_data(file_path):
    """Load analysis JSON file."""
    with open(file_path, 'r') as file:
        return json.load(file)


def parse_base_offset_from_urdf(urdf_file_path, joint_name):
    """
    Parse the base offset from URDF file.
    
    Args:
        urdf_file_path: Path to the URDF file
        joint_name: Name of the joint to extract the offset from (default: left_ur_arm_shoulder_pan_joint)
    
    Returns:
        float: The z-component of the origin xyz attribute (base offset in meters)
    """
    tree = ET.parse(urdf_file_path)
    root = tree.getroot()
    
    # Find the joint with the specified name
    for joint in root.findall('.//joint'):
        if joint.get('name') == joint_name:
            origin = joint.find('origin')
            if origin is not None and origin.get('xyz') is not None:
                xyz_str = origin.get('xyz')
                xyz_values = [float(x) for x in xyz_str.split()]
                if len(xyz_values) >= 3:
                    z_value = xyz_values[2]  # z is the third component
                    logger.info(f'Parsed base offset from URDF joint "{joint_name}": {xyz_values} -> z={z_value}')
                    return z_value
    
    raise ValueError(f'Could not find joint "{joint_name}" or origin xyz in URDF file: {urdf_file_path}')


def analyze_base_mocap_variation(takes):
    """
    Analyze base mocap position and orientation variation.
    Returns position and orientation statistics.
    """
    all_base_mocap_pos = []
    all_base_mocap_quats = []
    take_boundaries = []  # Track where each take starts
    
    for take in takes:
        take_boundaries.append(len(all_base_mocap_pos))  # Record start index of this take
        for entry in take['raw_data']:
            base_mocap_pose = entry.get("base_mocap_pose", [])
            if base_mocap_pose:
                all_base_mocap_pos.append(base_mocap_pose[0])
                all_base_mocap_quats.append(base_mocap_pose[1])
    
    all_base_mocap_pos = np.array(all_base_mocap_pos)
    all_base_mocap_quats = np.array(all_base_mocap_quats)
    
    # Position analysis
    base_mocap_pos_mean = np.mean(all_base_mocap_pos, axis=0)
    base_pos_distances = np.linalg.norm(all_base_mocap_pos - base_mocap_pos_mean, axis=1)
    
    logger.info('Base mocap position statistics:')
    logger.info(f'  Mean position: {base_mocap_pos_mean * 1000} mm')
    logger.info(f'  Max distance from mean: {max(base_pos_distances) * 1000:.2f} mm')
    logger.info(f'  Min distance from mean: {min(base_pos_distances) * 1000:.2f} mm')
    logger.info(f'  Average distance from mean: {np.mean(base_pos_distances) * 1000:.2f} mm')
    
    # Orientation analysis - convert quaternions to rotation matrices
    rotation_matrices = np.array([pp.tform_from_pose(([0,0,0], quat))[:3, :3] 
                                  for quat in all_base_mocap_quats])
    
    # Extract x, y, z axes from each rotation matrix
    x_axes = rotation_matrices[:, :, 0]  # First column is x-axis
    y_axes = rotation_matrices[:, :, 1]  # Second column is y-axis
    z_axes = rotation_matrices[:, :, 2]  # Third column is z-axis
    
    # Compute mean axes
    mean_x_axis = Vector(np.mean(x_axes, axis=0)).unit()
    mean_y_axis = Vector(np.mean(y_axes, axis=0)).unit()
    mean_z_axis = Vector(np.mean(z_axes, axis=0)).unit()
    
    # Compute angle deviations
    x_deviations = [np.rad2deg(Vector(axis).angle_between(mean_x_axis)) for axis in x_axes]
    y_deviations = [np.rad2deg(Vector(axis).angle_between(mean_y_axis)) for axis in y_axes]
    z_deviations = [np.rad2deg(Vector(axis).angle_between(mean_z_axis)) for axis in z_axes]
    
    logger.info('Base mocap orientation statistics:')
    max_x_deg = max(x_deviations)
    max_y_deg = max(y_deviations)
    max_z_deg = max(z_deviations)
    x_dev_mm_1m = np.tan(np.deg2rad(max_x_deg)) * 1000
    y_dev_mm_1m = np.tan(np.deg2rad(max_y_deg)) * 1000
    z_dev_mm_1m = np.tan(np.deg2rad(max_z_deg)) * 1000
    logger.info(f'  Max angle deviation for x-axis: {max_x_deg:.2f} degrees (equiv. to {x_dev_mm_1m:.1f} mm over 1 m)')
    logger.info(f'  Max angle deviation for y-axis: {max_y_deg:.2f} degrees (equiv. to {y_dev_mm_1m:.1f} mm over 1 m)')
    logger.info(f'  Max angle deviation for z-axis: {max_z_deg:.2f} degrees (equiv. to {z_dev_mm_1m:.1f} mm over 1 m)')
    return {
        'positions': all_base_mocap_pos,
        'quaternions': all_base_mocap_quats,
        'pos_mean': base_mocap_pos_mean,
        'pos_distances': base_pos_distances,
        'mean_axes': (mean_x_axis, mean_y_axis, mean_z_axis),
        'axis_deviations': (x_deviations, y_deviations, z_deviations),
        'take_boundaries': take_boundaries
    }


def visualize_base_mocap_variation(mocap_data, joint_name, output_dir):
    """Visualize base mocap position and orientation variations."""
    # Position deviations plot
    fig, ax = plt.subplots(figsize=(10, 6))
    indices = np.arange(len(mocap_data['pos_distances']))
    x_deviations = np.abs(mocap_data['positions'][:, 0] - mocap_data['pos_mean'][0]) * 1000
    y_deviations = np.abs(mocap_data['positions'][:, 1] - mocap_data['pos_mean'][1]) * 1000
    z_deviations = np.abs(mocap_data['positions'][:, 2] - mocap_data['pos_mean'][2]) * 1000
    
    ax.plot(indices, x_deviations, 'r-', label='X-axis')
    ax.plot(indices, y_deviations, 'g-', label='Y-axis')
    ax.plot(indices, z_deviations, 'b-', label='Z-axis')
    ax.plot(indices, mocap_data['pos_distances'] * 1000, 'k--', label='Total distance')
    
    # Add vertical separators for each data take
    take_boundaries = mocap_data.get('take_boundaries', [])
    for i, boundary in enumerate(take_boundaries[1:], start=1):  # Skip first boundary (index 0)
        ax.axvline(x=boundary, color='gray', linestyle='--', alpha=0.7, linewidth=1)
        ax.text(boundary, ax.get_ylim()[1] * 0.95, f'T{i}', fontsize=8, ha='center', va='top', color='gray')
    
    ax.set_xlabel('Sample index')
    ax.set_ylabel('Distance from mean (mm)')
    ax.set_title(f'{joint_name} - Base Mocap Position Deviations by Axis')
    ax.legend()
    plt.savefig(os.path.join(output_dir, f'{joint_name}_base_mocap_pos_deviation.png'))
    plt.close()
    
    # Orientation deviations plot
    fig, ax = plt.subplots()
    indices = list(range(len(mocap_data['axis_deviations'][0])))
    ax.plot(indices, mocap_data['axis_deviations'][0], 'r-', label='X-axis')
    ax.plot(indices, mocap_data['axis_deviations'][1], 'g-', label='Y-axis')
    ax.plot(indices, mocap_data['axis_deviations'][2], 'b-', label='Z-axis')
    
    # Add vertical separators for each data take
    for i, boundary in enumerate(take_boundaries[1:], start=1):  # Skip first boundary (index 0)
        ax.axvline(x=boundary, color='gray', linestyle='--', alpha=0.7, linewidth=1)
        ax.text(boundary, ax.get_ylim()[1] * 0.95, f'T{i}', fontsize=8, ha='center', va='top', color='gray')
    
    ax.set_xlabel('Sample index')
    ax.set_ylabel('Angle deviation (degrees)')
    ax.set_title(f'{joint_name} - Base Mocap Orientation Deviations')
    ax.legend()
    plt.savefig(os.path.join(output_dir, f'{joint_name}_base_mocap_axis_deviation.png'))
    plt.close()


def analyze_circle_centers(centers, normals, joint_name, output_dir):
    """
    Analyze circle centers and their distances.
    Visualize centers and compute statistics.
    """
    centers = np.array(centers)
    normals = np.array(normals)
    
    # Compute distances between all pairs of centers
    n_centers = len(centers)
    center_distances = []
    for i in range(n_centers):
        for j in range(i + 1, n_centers):
            dist = np.linalg.norm(centers[i] - centers[j])
            center_distances.append(dist)
    
    logger.info(f'{joint_name} circle centers analysis:')
    logger.info(f'  Number of centers: {n_centers}')
    logger.info(f'  Min distance between centers: {min(center_distances) * 1000:.2f} mm')
    logger.info(f'  Max distance between centers: {max(center_distances) * 1000:.2f} mm')
    logger.info(f'  Average distance between centers: {np.mean(center_distances) * 1000:.2f} mm')
    
    if min(center_distances) < 0.01:
        logger.warning(f'  WARNING: Some circle centers are very close (< 10mm). Line fitting may be unreliable.')
    
    # Compute fitted line for visualization (same logic as fit_line_to_centers)
    # Compute average normal
    N_avg = np.mean(normals, axis=0)
    N_avg = N_avg / np.linalg.norm(N_avg)  # Normalize
    
    # Form plane using averaged center and average normal
    center_avg = np.mean(centers, axis=0)
    plane = Plane(point=center_avg, normal=N_avg)
    
    # Project all centers onto the plane
    projected_centers = [plane.project_point(Point(c)) for c in centers]
    projected_centers = np.array([p for p in projected_centers])
    
    # Average of projected points is the anchor point
    p_anchor = np.mean(projected_centers, axis=0)
    
    # Create line
    fitted_line = Line(point=p_anchor, direction=N_avg)
    
    # Compute distances from centers to fitted line and projections
    center_to_line_distances = []
    center_projections = []
    for c in centers:
        proj_point = fitted_line.project_point(Point(c))
        center_projections.append(proj_point)
        dist = fitted_line.distance_point(Point(c))
        center_to_line_distances.append(dist)
    
    center_projections = np.array(center_projections)
    
    # Visualize centers with fitted line and projections
    fig = plt.figure(figsize=(12, 10))
    ax = fig.add_subplot(projection='3d')
    
    # Plot circle centers
    ax.scatter(centers[:, 0] * 1000, centers[:, 1] * 1000, centers[:, 2] * 1000, 
               c='g', s=50, label='Circle centers', alpha=0.7)
    
    # Plot fitted line
    line_length = max(center_distances) * 1.5 if center_distances else 0.5
    line_points = np.array([p_anchor + t * N_avg for t in np.linspace(-line_length/2, line_length/2, 100)])
    ax.plot(line_points[:, 0] * 1000, line_points[:, 1] * 1000, line_points[:, 2] * 1000, 
            'b-', linewidth=2, label='Fitted line')
    
    # Plot projections on line
    ax.scatter(center_projections[:, 0] * 1000, center_projections[:, 1] * 1000, center_projections[:, 2] * 1000, 
               c='r', s=30, marker='x', label='Projections on line', alpha=0.7)
    
    # Draw lines from centers to their projections and annotate distances
    for i, (center, proj, dist) in enumerate(zip(centers, center_projections, center_to_line_distances)):
        # Draw line from center to projection
        ax.plot([center[0] * 1000, proj[0] * 1000], 
                [center[1] * 1000, proj[1] * 1000], 
                [center[2] * 1000, proj[2] * 1000], 
                'k--', alpha=0.3, linewidth=1)
        
        # Annotate distance at midpoint
        mid_point = (center + proj) / 2
        dist_mm = dist * 1000
        ax.text(mid_point[0] * 1000, mid_point[1] * 1000, mid_point[2] * 1000, 
                f'{dist_mm:.2f}mm', fontsize=8, alpha=0.7)
    
    ax.set_xlabel('X (mm)')
    ax.set_ylabel('Y (mm)')
    ax.set_zlabel('Z (mm)')
    ax.set_title(f'{joint_name} - Circle Centers with Fitted Line')
    ax.legend()
    plt.savefig(os.path.join(output_dir, f'{joint_name}_circle_centers.png'), dpi=150)
    plt.show()  # Keep plot open for interaction
    plt.close()
    
    return center_distances


def fit_line_to_centers(centers, normals, joint_name):
    """
    Fit a line to circle centers.
    Procedure:
    1. Take average of all circle normals (N_avg)
    2. Take one circle center and form a plane using that point as origin and N_avg as normal
    3. Project all circle centers onto this plane
    4. Take average of projected points as anchor point, N_avg as direction
    """
    centers = np.array(centers)
    normals = np.array(normals)
    
    # Compute average normal
    N_avg = np.mean(normals, axis=0)
    N_avg = N_avg / np.linalg.norm(N_avg)  # Normalize
    
    logger.info(f'{joint_name} line fitting:')
    logger.info(f'  Average circle normal: {N_avg}')
    
    # Visualize angle differences from mean normal
    angle_diffs = []
    for n in normals:
        v = Vector(n)
        angle_diff = np.rad2deg(v.angle_between(Vector(N_avg)))
        angle_diffs.append(angle_diff)
    
    logger.info(f'  Angle differences from mean normal (deg): {[f"{a:.2f}" for a in angle_diffs]}')
    logger.info(f'  Max angle difference: {max(angle_diffs):.2f} degrees')
    
    # Form plane using averaged center and average normal
    center_avg = np.mean(centers, axis=0)
    plane = Plane(point=center_avg, normal=N_avg)
    
    # Project all centers onto the plane
    projected_centers = [plane.project_point(Point(c)) for c in centers]
    projected_centers = np.array([p for p in projected_centers])
    
    # Average of projected points is the anchor point
    p_anchor = np.mean(projected_centers, axis=0)
    
    # Create line
    fitted_line = Line(point=p_anchor, direction=N_avg)
    
    logger.info(f'  Fitted line point: {p_anchor * 1000} mm')
    logger.info(f'  Fitted line direction: {N_avg}')
    
    # Compute distances from centers to fitted line
    center_to_line_distances = [fitted_line.distance_point(Point(c)) for c in centers]
    logger.info(f'  Max distance from centers to fitted line: {max(center_to_line_distances) * 1000:.2f} mm')
    logger.info(f'  Average distance from centers to fitted line: {np.mean(center_to_line_distances) * 1000:.2f} mm')
    
    return fitted_line, angle_diffs, center_to_line_distances


def compute_plane_plane_intersection(plane1_point, plane1_normal, plane2_point, plane2_normal):
    """
    Compute intersection of two planes using skspatial library.
    Returns a Line object representing the intersection curve.
    """
    # Create Plane objects from skspatial
    plane1 = Plane(point=plane1_point, normal=plane1_normal)
    plane2 = Plane(point=plane2_point, normal=plane2_normal)
    
    # Use skspatial's built-in intersect_plane method
    intersection_line = plane1.intersect_plane(plane2)
    
    return intersection_line


def compute_base_frame(j0_line, j1_line, base_offset=0.1625):
    """
    Compute robot base frame from j0 and j1 fitted lines.
    
    Steps:
    1. j0 line gives z-axis (v0)
    2. j1 line gives y-axis (v1)
    3. Find intersection of planes (p0, v1) and (p1, v1) where plane is formed by point as origin and vector as z-axis
    4. Find closest point on intersection curve to p1, call this p01
    5. Move p01 in negative direction of normalized v0 by base_offset to get base origin p_b
    6. Construct 4x4 transformation matrix with p_b as origin, v0 as z-axis, v1 as y-axis
    
    Note: The plane-plane intersection interpretation:
    - Plane0: through p0, with z-axis = v1 (so normal = v1)
    - Plane1: through p1, with z-axis = v1 (so normal = v1)
    These are parallel planes. If they don't intersect, we find the closest point between
    the j0 and j1 lines as an approximation.
    """
    p0 = j0_line.point
    v0 = j0_line.direction
    v0 = v0 / np.linalg.norm(v0)  # Normalize
    
    p1 = j1_line.point
    v1 = j1_line.direction
    v1 = v1 / np.linalg.norm(v1)  # Normalize
    
    logger.info('Computing base frame:')
    logger.info(f'  j0 line point: {p0 * 1000} mm')
    logger.info(f'  j0 line direction (z-axis): {v0}')
    logger.info(f'  j1 line point: {p1 * 1000} mm')
    logger.info(f'  j1 line direction (y-axis): {v1}')
    
    # Form planes as described:
    # Plane0: origin is p0, normal is v1
    # Plane1: origin is p1, normal is the cross product of v0 and v1
    v0_cross_v1 = np.cross(v0, v1)
    v0_cross_v1_norm = np.linalg.norm(v0_cross_v1)
    if v0_cross_v1_norm < 1e-8:
        raise RuntimeError("v0 and v1 are parallel - cannot compute cross product for plane1 normal!")
    v0_cross_v1_normalized = v0_cross_v1 / v0_cross_v1_norm
    
    plane0 = Plane(point=p0, normal=v1)
    plane1 = Plane(point=p1, normal=v0_cross_v1_normalized)
    
    # The plane definitions are now:
    #   plane0: through p0, normal v1
    #   plane1: through p1, normal (v0 × v1)
    # They are not generally parallel, so their intersection is a line.
    # The intersection line can be parameterized, and we want the point on that line
    # that is closest to p1 (or any other determination step).

    # Compute direction of intersection line
    # Intersection direction is cross product of the two plane normals
    intersection_direction = np.cross(v1, v0_cross_v1_normalized)
    norm_dir = np.linalg.norm(intersection_direction)
    if norm_dir < 1e-8:
        # Planes should not be parallel here. Raise an error.
        raise RuntimeError("Planes appear parallel during base frame computation; check line directions!")
    else:
        intersection_direction = intersection_direction / norm_dir  # normalize

        # Use compute_plane_plane_intersection as the primary method (uses skspatial)
        intersection_result = compute_plane_plane_intersection(
            p0, v1, p1, v0_cross_v1_normalized
        )
        
        # Extract intersection line from result (skspatial Line object)
        pp_line_point = intersection_result.point
        pp_line_direction = intersection_result.direction
        pp_line_direction = pp_line_direction / np.linalg.norm(pp_line_direction)  # Ensure normalized
        
        # Project p1 onto intersection line to get p01
        line_vec = pp_line_direction
        p1_to_line = p1 - pp_line_point
        proj_len = np.dot(p1_to_line, line_vec)
        p01 = pp_line_point + proj_len * line_vec
        
        # For plotting in the final 3D plot, save the intersection line and p01
        plane_plane_intersection_info = {}
        plane_plane_intersection_info['anchor'] = pp_line_point
        plane_plane_intersection_info['direction'] = pp_line_direction
        plane_plane_intersection_info['p01'] = p01
        # Store plane information for visualization
        plane_plane_intersection_info['plane0'] = {'point': p0, 'normal': v1}
        plane_plane_intersection_info['plane1'] = {'point': p1, 'normal': v0_cross_v1_normalized}
        
        logger.info(f'  Intersection direction: {pp_line_direction}')
        logger.info(f'  Intersection point (closest to p1): {p01 * 1000} mm')
        logger.info(f'  Intersection anchor: {pp_line_point * 1000} mm')    

        # Attach intersection info to return or global state for plotting
        # Assumes you return/interact with this info after computation,
        # e.g. use as part of function output, or store to self/var
        result_plane_plane_intersection_info = plane_plane_intersection_info

    # ! note that this is still in the base mocap frame
    p_b = p01 - base_offset * v0
    
    logger.info(f'  Base origin p_b (after offset): {p_b * 1000} mm')
    
    # Construct frame: z-axis = v0, y-axis = v1, x-axis = y × z
    z_axis = v0
    x_axis = v1
    y_axis = np.cross(z_axis, x_axis)
    y_axis = y_axis / np.linalg.norm(x_axis)
    
    # Recompute z-axis to ensure orthogonality
    z_axis = np.cross(x_axis, y_axis)
    z_axis = z_axis / np.linalg.norm(z_axis)
    
    logger.info(f'  Base frame axes:')
    logger.info(f'    x-axis: {x_axis}')
    logger.info(f'    y-axis: {y_axis}')
    logger.info(f'    z-axis: {z_axis}')
    
    # Construct 4x4 transformation matrix
    transformation_matrix = np.eye(4)
    transformation_matrix[:3, 0] = x_axis
    transformation_matrix[:3, 1] = y_axis
    transformation_matrix[:3, 2] = z_axis
    transformation_matrix[:3, 3] = p_b
    
    return transformation_matrix, p_b, (x_axis, y_axis, z_axis), result_plane_plane_intersection_info


def plot_plane(ax, point, normal, size=0.3, color='cyan', alpha=0.3, label=None):
    """
    Plot a plane in 3D.
    
    Args:
        ax: 3D axes object
        point: Point on the plane (3D array)
        normal: Normal vector of the plane (3D array, should be normalized)
        size: Size of the plane patch (in meters, will be converted to mm)
        color: Color of the plane
        alpha: Transparency
        label: Label for legend
    """
    # Find two orthogonal vectors in the plane
    # First, find a vector perpendicular to the normal
    if abs(normal[2]) < 0.9:
        # Use z-axis as reference
        v1 = np.cross(normal, np.array([0, 0, 1]))
    else:
        # Use x-axis as reference
        v1 = np.cross(normal, np.array([1, 0, 0]))
    v1 = v1 / np.linalg.norm(v1)
    
    # Second vector is perpendicular to both normal and v1
    v2 = np.cross(normal, v1)
    v2 = v2 / np.linalg.norm(v2)
    
    # Create a grid of points on the plane
    u = np.linspace(-size, size, 20)
    v = np.linspace(-size, size, 20)
    U, V = np.meshgrid(u, v)
    
    # Generate points on the plane
    X = point[0] + U * v1[0] + V * v2[0]
    Y = point[1] + U * v1[1] + V * v2[1]
    Z = point[2] + U * v1[2] + V * v2[2]
    
    # Convert to mm and plot
    surf = ax.plot_surface(X * 1000, Y * 1000, Z * 1000, 
                           color=color, alpha=alpha, edgecolor='none')
    # Set label for legend (plot_surface doesn't support label directly)
    if label is not None:
        surf._facecolors2d = surf._facecolor3d
        surf._edgecolors2d = surf._edgecolor3d
        surf.set_label(label)


def visualize_results(j0_data, j1_data, j0_line, j1_line, base_frame_tf, output_dir, intersection_info=None):
    """Visualize the fitted lines and computed base frame."""
    fig = plt.figure(figsize=(12, 10))
    ax = fig.add_subplot(projection='3d')
    
    # Plot j0 circle centers and fitted line
    j0_centers = np.array([take['center'] for take in j0_data['takes']])
    ax.scatter(j0_centers[:, 0] * 1000, j0_centers[:, 1] * 1000, j0_centers[:, 2] * 1000, 
               c='b', s=50, alpha=0.6, label='j0 centers')
    # Plot line in mm - need to convert line points
    line_points_j0 = np.array([j0_line.point + t * j0_line.direction for t in np.linspace(-0.3, 0.3, 100)])
    ax.plot(line_points_j0[:, 0] * 1000, line_points_j0[:, 1] * 1000, line_points_j0[:, 2] * 1000, 
            'b-', linewidth=2, label='j0 fitted line')
    
    # Plot j1 circle centers and fitted line
    j1_centers = np.array([take['center'] for take in j1_data['takes']])
    ax.scatter(j1_centers[:, 0] * 1000, j1_centers[:, 1] * 1000, j1_centers[:, 2] * 1000, 
               c='r', s=50, alpha=0.6, label='j1 centers')
    # Plot line in mm - need to convert line points
    line_points_j1 = np.array([j1_line.point + t * j1_line.direction for t in np.linspace(-0.3, 0.3, 100)])
    ax.plot(line_points_j1[:, 0] * 1000, line_points_j1[:, 1] * 1000, line_points_j1[:, 2] * 1000, 
            'r-', linewidth=2, label='j1 fitted line')
    
    # Plot intersection line (c01) and p01 if available
    if intersection_info is not None:
        p_int = intersection_info.get('anchor')
        intersection_direction = intersection_info.get('direction')
        p01 = intersection_info.get('p01')
        
        if p_int is not None and intersection_direction is not None:
            # Plot intersection line (c01)
            line_length = 0.5  # meters, adjust as needed
            intersection_line_points = np.array([
                p_int + t * intersection_direction 
                for t in np.linspace(-line_length, line_length, 100)
            ])
            ax.plot(intersection_line_points[:, 0] * 1000, 
                   intersection_line_points[:, 1] * 1000, 
                   intersection_line_points[:, 2] * 1000, 
                   'm-', linewidth=2, linestyle='--', alpha=0.8, label='Intersection line (c01)')
        
        if p01 is not None:
            # Plot and label p01 point
            ax.scatter([p01[0] * 1000], [p01[1] * 1000], [p01[2] * 1000], 
                      c='orange', s=150, marker='o', label='p01', edgecolors='darkorange', linewidths=2)
            # Add text label
            ax.text(p01[0] * 1000, p01[1] * 1000, p01[2] * 1000, 
                   '  p01', fontsize=12, fontweight='bold', color='darkorange')
        
        # Plot the two planes
        plane0_info = intersection_info.get('plane0')
        plane1_info = intersection_info.get('plane1')
        
        if plane0_info is not None:
            plot_plane(ax, plane0_info['point'], plane0_info['normal'], 
                      size=1.0, color='cyan', alpha=0.3, label='Plane0 (p0, v1)')
        
        if plane1_info is not None:
            plot_plane(ax, plane1_info['point'], plane1_info['normal'], 
                      size=1.0, color='yellow', alpha=0.3, label='Plane1 (p1, v0×v1)')
    
    # Plot base frame
    origin = base_frame_tf[:3, 3] * 1000  # Convert to mm
    x_axis = base_frame_tf[:3, 0]
    y_axis = base_frame_tf[:3, 1]
    z_axis = base_frame_tf[:3, 2]
    
    axis_length = 0.2 * 1000  # Convert to mm
    ax.quiver(origin[0], origin[1], origin[2], 
              x_axis[0], x_axis[1], x_axis[2], 
              length=axis_length, color='r', arrow_length_ratio=0.3, linewidth=2, label='Base X')
    ax.quiver(origin[0], origin[1], origin[2], 
              y_axis[0], y_axis[1], y_axis[2], 
              length=axis_length, color='g', arrow_length_ratio=0.3, linewidth=2, label='Base Y')
    ax.quiver(origin[0], origin[1], origin[2], 
              z_axis[0], z_axis[1], z_axis[2], 
              length=axis_length, color='b', arrow_length_ratio=0.3, linewidth=2, label='Base Z')
    
    ax.scatter([origin[0]], [origin[1]], [origin[2]], 
               c='k', s=100, marker='*', label='Base origin')

    # Draw a unit pose at the origin for reference (red=X, green=Y, blue=Z)
    unit_origin = np.array([0, 0, 0])
    unit_length = 0.10 * 1000  # 80mm for visual clarity

    # Use lighter/transparent versions of the base axes colors to visually distinguish the reference unit axes
    ax.quiver(unit_origin[0], unit_origin[1], unit_origin[2],
              1, 0, 0,
              length=unit_length, color=(1, 0.7, 0.7, 0.6), arrow_length_ratio=0.3, linewidth=2, label='Unit X (ref)')
    ax.quiver(unit_origin[0], unit_origin[1], unit_origin[2],
              0, 1, 0,
              length=unit_length, color=(0.7, 1, 0.7, 0.6), arrow_length_ratio=0.3, linewidth=2, label='Unit Y (ref)')
    ax.quiver(unit_origin[0], unit_origin[1], unit_origin[2],
              0, 0, 1,
              length=unit_length, color=(0.6, 0.8, 1.0, 0.6), arrow_length_ratio=0.3, linewidth=2, label='Unit Z (ref)')
    ax.set_xlabel('X (mm)')
    ax.set_ylabel('Y (mm)')
    ax.set_zlabel('Z (mm)')
    ax.set_title('Calibration Analysis - Fitted Lines and base_mocap_from_arm_base_link')
    ax.legend()
    plt.savefig(os.path.join(output_dir, 'calibration_analysis_result.png'), dpi=150)
    plt.show()  # Keep plot open for interaction
    plt.close()


def main():
    """Main function."""
    logger.info('=' * 80)
    logger.info('Starting calibration analysis')
    logger.info('=' * 80)
    
    # Parse base offset from URDF
    logger.info(f'Parsing base offset from URDF: {URDF_FILE}')
    BASE_OFFSET = parse_base_offset_from_urdf(URDF_FILE, SHOULDER_PAN_JOINT_NAME)
    logger.info(f'Base offset: {BASE_OFFSET} m ({BASE_OFFSET * 1000:.4f} mm)')
    
    # Load data
    logger.info(f'Loading j0 data from: {j0_data_file_path}')
    j0_data = load_analysis_data(j0_data_file_path)
    
    logger.info(f'Loading j1 data from: {j1_data_file_path}')
    j1_data = load_analysis_data(j1_data_file_path)
    
    logger.info(f'j0 has {len(j0_data["takes"])} takes')
    logger.info(f'j1 has {len(j1_data["takes"])} takes')
    
    # Analyze base mocap variation for j0
    logger.info('\n' + '=' * 80)
    logger.info('Analyzing j0 base mocap variation')
    logger.info('=' * 80)
    j0_mocap_data = analyze_base_mocap_variation(j0_data['takes'])
    visualize_base_mocap_variation(j0_mocap_data, 'j0', output_dir)
    
    # Analyze base mocap variation for j1
    logger.info('\n' + '=' * 80)
    logger.info('Analyzing j1 base mocap variation')
    logger.info('=' * 80)
    j1_mocap_data = analyze_base_mocap_variation(j1_data['takes'])
    visualize_base_mocap_variation(j1_mocap_data, 'j1', output_dir)
    
    # Extract circle centers and normals
    j0_centers = [take['center'] for take in j0_data['takes']]
    j0_normals = [take['normal'] for take in j0_data['takes']]
    j1_centers = [take['center'] for take in j1_data['takes']]
    j1_normals = [take['normal'] for take in j1_data['takes']]
    
    # Analyze circle centers
    logger.info('\n' + '=' * 80)
    logger.info('Analyzing j0 circle centers')
    logger.info('=' * 80)
    analyze_circle_centers(j0_centers, j0_normals, 'j0', output_dir)
    
    logger.info('\n' + '=' * 80)
    logger.info('Analyzing j1 circle centers')
    logger.info('=' * 80)
    analyze_circle_centers(j1_centers, j1_normals, 'j1', output_dir)
    
    # Fit lines to centers
    logger.info('\n' + '=' * 80)
    logger.info('Fitting line to j0 circle centers')
    logger.info('=' * 80)
    j0_line, j0_angle_diffs, j0_line_distances = fit_line_to_centers(j0_centers, j0_normals, 'j0')
    
    logger.info('\n' + '=' * 80)
    logger.info('Fitting line to j1 circle centers')
    logger.info('=' * 80)
    j1_line, j1_angle_diffs, j1_line_distances = fit_line_to_centers(j1_centers, j1_normals, 'j1')
    
    # Compute base frame
    logger.info('\n' + '=' * 80)
    logger.info('Computing robot base frame')
    logger.info('=' * 80)
    base_frame_tf, base_origin, base_axes, intersection_info = compute_base_frame(j0_line, j1_line, BASE_OFFSET)
    
    # Convert to pose (position, quaternion)
    base_frame_pose = pp.pose_from_tform(base_frame_tf)
    
    logger.info('\n' + '=' * 80)
    logger.info('Final base frame transformation:')
    logger.info('=' * 80)
    logger.info(f'Origin: {np.array(base_frame_pose[0]) * 1000} mm')
    logger.info(f'Quaternion: {base_frame_pose[1]}')
    # Create a display matrix with position in mm
    display_matrix = base_frame_tf.copy()
    # display_matrix[:3, 3] = base_frame_tf[:3, 3] * 1000
    logger.info(f'\nTransformation matrix:\n{display_matrix}')
    
    # Visualize results
    logger.info('\nVisualizing results...')
    visualize_results(j0_data, j1_data, j0_line, j1_line, base_frame_tf, output_dir, intersection_info)
    
    # Save results
    output_file = os.path.join(output_dir, 'base_frame_calibration.json')
    result = {
        'base_mocap_from_arm_base_link': base_frame_tf.tolist(),
        'j0_line': {
            'point': list(j0_line.point),
            'direction': list(j0_line.direction)
        },
        'j1_line': {
            'point': list(j1_line.point),
            'direction': list(j1_line.direction)
        },
        'base_offset': BASE_OFFSET
    }
    
    with open(output_file, 'w') as f:
        json.dump(result, f, indent=4)
    
    logger.info(f'\nResults saved to: {output_file}')
    logger.info('=' * 80)
    logger.info('Calibration analysis complete!')
    logger.info('=' * 80)


if __name__ == '__main__':
    main()
